/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_billing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class Discounts extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    String discountID = null;
    StudentBill studentBill = null;
    Add_Discount add = null;
    Discounts main = this;
    JMenuItem Update = new JMenuItem("Update discount");
    JPopupMenu menu = new JPopupMenu();

    /**
     * Creates new form StudentInfo
     */
    public Discounts() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        loadDiscounts();

        Update.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (add == null) {
                    add = new Add_Discount();
                    add.set_Update(true, discountID, main);
                    add.load_discountData();
                    add.setVisible(true);

                } else {

                    add.set_Update(true, discountID, main);
                    add.load_discountData();
                    add.setVisible(true);
                }

            }
        });

        menu.add(Update);

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    menu.show(e.getComponent(), e.getX(), e.getY());
                }
            }

        });

        setBounds(340, 0, 480, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_Update_Select = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Button_Update_Select1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Discounts");
        setMaximumSize(new java.awt.Dimension(1200, 550));
        setMinimumSize(new java.awt.Dimension(1029, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(480, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Discount ID", "Discount Name", "Value", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, 420));

        Button_Update_Select.setText("Add new Discount");
        Button_Update_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Update_SelectActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Update_Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 150, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Discounts List");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, -1));

        Button_Update_Select1.setText("Close");
        Button_Update_Select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Update_Select1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Update_Select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Update_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Update_SelectActionPerformed
        // TODO add your handling code here:
        if (add == null) {
            add = new Add_Discount();
            add.main = this;
            add.setVisible(true);
        } else {
            add.setVisible(true);
            add.main = this;
        }
    }//GEN-LAST:event_Button_Update_SelectActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 0)));
        discountID = String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 0));

    }//GEN-LAST:event_jTable1MouseClicked

    private void Button_Update_Select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Update_Select1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Button_Update_Select1ActionPerformed

    void loadDiscounts() {
        try {
            model.setRowCount(0);
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            int idDiscount = 0;
            ps = c.prepareStatement("Select idDiscounts, Discount_Name, Value,Type from discounts");
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Discounts.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setDiscountId() {
        studentBill.discountID = discountID;

    }

    public void setStudentBill(StudentBill a) {
        studentBill = a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_Update_Select;
    public javax.swing.JButton Button_Update_Select1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
