/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_billing;

import java.awt.Component;
import java.awt.event.WindowEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.awt.WindowClosingListener;
import sun.net.www.content.image.jpeg;

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class MainFrame extends javax.swing.JFrame {

    public String UserName;
    Section_Manager section = null;
    private int User;
    Login login;
    Accounting accounting = null;
    Section section1 = null;
    Activity_Log activity_Log;
    boolean Registrar = false, Princiap = true;
    DBConnection connection;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            DBConnection.ReadIPaddress();

            initComponents();
            RefreshTime();
            jMenuRegistrar.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuRegistrar = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuCashar = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuPrinsipals = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuViewing = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuFinance = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Digos Central Adventist Academy Billing and Management System");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(97, 8, 0, 0));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jToolBar1.setRollover(true);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("  Add New Student");
        jButton4.setToolTipText("");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText(" Billing and Information");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText(" Statement of Accounts");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText(" Invoice");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setText(" User Accounts");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setText("Accounting");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Log out");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        DesktopPane.setBackground(new java.awt.Color(51, 51, 51));
        DesktopPane.setMaximumSize(new java.awt.Dimension(1200, 550));
        DesktopPane.setMinimumSize(new java.awt.Dimension(1200, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DCAA Logo without Background.png"))); // NOI18N
        DesktopPane.add(jLabel1);
        jLabel1.setBounds(50, 300, 240, 230);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digos Central Adventist Academy");
        DesktopPane.add(jLabel2);
        jLabel2.setBounds(290, 340, 840, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Billing and Management System");
        DesktopPane.add(jLabel3);
        jLabel3.setBounds(340, 410, 800, 58);

        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 550));

        Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Time.setText("Time: today");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 330, 20));

        UserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLabel.setText("User:Jamie");
        getContentPane().add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 180, 20));

        jMenu1.setText("System");

        jMenuItem3.setText("Fees");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Category of Charges");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Sections");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Discounts");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Departments");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setText("School Year");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem9.setText("User Accounts");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem21.setText("Database IP ");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jMenuItem20.setText("Activity Log");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem20);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Shortcuts");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Add new Student");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem8.setText("Billing and Information");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem10.setText("Statement of Accounts");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem11.setText("Invoice");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem12.setText("User accounts");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem13.setText("Accounting");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenuRegistrar.setText("Registrar");
        jMenuRegistrar.setEnabled(false);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem14.setText("Add New Student");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem15.setText("Student Info");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(jMenuItem15);

        jMenuBar1.add(jMenuRegistrar);

        jMenuCashar.setText("Cashering");

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem16.setText("Billing");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenuCashar.add(jMenuItem16);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem17.setText("Invoice");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuCashar.add(jMenuItem17);

        jMenuBar1.add(jMenuCashar);

        jMenuPrinsipals.setText("Principals");

        jMenuItem19.setText("Sections");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenuPrinsipals.add(jMenuItem19);

        jMenuBar1.add(jMenuPrinsipals);

        jMenuViewing.setText("Viewing");

        jMenuItem18.setText("Statements");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenuViewing.add(jMenuItem18);

        jMenuBar1.add(jMenuViewing);

        jMenuFinance.setText("Finance");
        jMenuBar1.add(jMenuFinance);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Statements statements = null;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if (statements == null) {
            statements = new Statements();
            statements.setBounds(62, -1, 1100, 550);
            DesktopPane.add(statements);
            statements.setVisible(true);
        } else {

            statements.setBounds(62, -1, 1100, 550);

            statements.setVisible(true);

        }
    }//GEN-LAST:event_jButton7ActionPerformed
    StudentInfo studentInfo = null;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (studentInfo == null) {
            studentInfo = new StudentInfo();
            studentInfo.USerID = String.valueOf(User);
            DesktopPane.add(studentInfo);

            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());
        } else {
            studentInfo.USerID = String.valueOf(User);
            DesktopPane.add(studentInfo);
            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Fees_Charges fee = null;
        if (fee == null) {
            fee = new Fees_Charges();
            fee.User = User;
            DesktopPane.add(fee);
            fee.show();

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    Departments departments = null;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        if (departments == null) {
            departments = new Departments();
            DesktopPane.add(departments);
            departments.show();

        } else {

            DesktopPane.add(departments);
            departments.show();

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    Category_of_Charges category_of_Charges = null;
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        if (category_of_Charges == null) {
            category_of_Charges = new Category_of_Charges();
            DesktopPane.add(category_of_Charges);
            category_of_Charges.setBounds(177, 26, 855, 495);
            category_of_Charges.show();

        } else {

            DesktopPane.add(category_of_Charges);
            category_of_Charges.setBounds(177, 26, 855, 495);
            category_of_Charges.show();

        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Section section = null;
        if (section == null) {
            section = new Section();
            DesktopPane.add(section);
            section.show();

        } else {
            DesktopPane.add(section);
            section.show();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Discounts discounts = null;
        if (discounts == null) {
            discounts = new Discounts();
            DesktopPane.add(discounts);
            discounts.show();

        } else {
            DesktopPane.add(discounts);
            discounts.show();

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    School_Year school_Year = null;
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        if (school_Year == null) {
            school_Year = new School_Year();
            DesktopPane.add(school_Year);
            school_Year.show();

        } else {
            DesktopPane.add(school_Year);
            school_Year.show();

        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    Student_List student_List = null;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if (student_List == null && !Registrar) {
            student_List = new Student_List();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);
            student_List.setVisible(true);

        } else if (Registrar && student_List == null) {
            student_List = new Student_List();
            student_List.set_RegistrarMode();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);

            student_List.setVisible(true);

        } else if (Registrar) {
            student_List.set_RegistrarMode();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            //DesktopPane.add(student_List);
            student_List.setVisible(true);

        } else if (!Princiap && student_List == null) {
            student_List = new Student_List();
            student_List.set_PrinciaplMode();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            //DesktopPane.add(student_List);
            student_List.setVisible(true);

        } else {
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            student_List.setVisible(true);

        }
    }//GEN-LAST:event_jButton5ActionPerformed
    Invoice invoice = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\

        if (invoice == null) {
            invoice = new Invoice();
            invoice.setUser(User);
            invoice.setVisible(true);
        } else {
            invoice.setUser(User);
            invoice.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    User_accounts user_accounts = null;
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        if (user_accounts == null) {
            user_accounts = new User_accounts();
            DesktopPane.add(user_accounts);
            user_accounts.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        if (accounting == null) {
            accounting = new Accounting();
            accounting.USer_id = String.valueOf(User);
            accounting.setVisible(true);
        } else {
            accounting.USer_id = String.valueOf(User);
            accounting.setVisible(true);

        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int op = JOptionPane.showConfirmDialog(locate(User, User), "System Log out?");

        if (op == 0) {
            try {
                login = new Login();
                login.setVisible(true);
                Activity_log("System Log out", "Log out");
                dispose();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (op == 1) {
            try {
                Activity_log("System Log out", "Log out and System Close");
                System.exit(0);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//    StudentInfo studentInfo = null;
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed

        if (studentInfo == null) {
            studentInfo = new StudentInfo();
            DesktopPane.add(studentInfo);

            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());
        } else {

            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());

        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    //Statements statements = null;
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        if (statements == null) {
            statements = new Statements();
            statements.setBounds(62, -1, 1100, 550);
            DesktopPane.add(statements);
            statements.setVisible(true);

        } else {
            statements.setBounds(62, -1, 1100, 550);
            DesktopPane.add(statements);
            statements.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    // Accounting accounting = null;
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

        if (accounting == null) {
            accounting = new Accounting();
            accounting.setVisible(true);
        } else {

            accounting.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    // Student_List student_List = null;
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        if (student_List == null) {
            student_List = new Student_List();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);

            student_List.setVisible(true);

        } else {

            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);

            student_List.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    // Invoice invoice = null;
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        if (invoice == null) {
            invoice = new Invoice();
            invoice.setUser(User);
            invoice.setVisible(true);
        } else {
            invoice.setUser(User);
            invoice.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    //User_accounts user_accounts = null;
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        if (user_accounts == null) {
            user_accounts = new User_accounts();
            user_accounts.UserId = User;
            DesktopPane.add(user_accounts);
            user_accounts.setVisible(true);
        } else {
            user_accounts.UserId = User;
            DesktopPane.add(user_accounts);
            user_accounts.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed
//StudentInfo studentInfo = null;
    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed

        if (studentInfo == null) {
            studentInfo = new StudentInfo();
            DesktopPane.add(studentInfo);

            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());
        } else {
            DesktopPane.add(studentInfo);

            studentInfo.setVisible(true);
            studentInfo.Fname.requestFocus();
            System.out.println(DesktopPane.getBounds());

        }

    }//GEN-LAST:event_jMenuItem14ActionPerformed

    //Statements statements = null;
    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        if (student_List == null) {
            student_List = new Student_List();
            student_List.set_RegistrarMode();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);

            student_List.setVisible(true);

        } else {
            student_List.set_RegistrarMode();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            //DesktopPane.add(student_List);
            student_List.setVisible(true);

        }

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    //Student_List student_List = null;
    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed

        if (student_List == null) {
            student_List = new Student_List();
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);
            student_List.setVisible(true);

        } else {
            student_List.main = this;
            student_List.UserID = String.valueOf(User);
            DesktopPane.add(student_List);
            student_List.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    //Invoice invoice = null;
    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        if (invoice == null) {
            invoice = new Invoice();
            invoice.setUser(User);
            invoice.setVisible(true);
        } else {

            invoice.setUser(User);
            invoice.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        if (activity_Log == null) {
            activity_Log = new Activity_Log();
            activity_Log.setVisible(true);
        } else {
            activity_Log.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Section section = null;
        if (section == null) {
            section = new Section();
            section.mainFrame = this;
            DesktopPane.add(section);
            section.show();

        } else {
            DesktopPane.add(section);
            section.show();
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        if (statements == null) {
            statements = new Statements();
            statements.setBounds(62, -1, 1100, 550);
            statements.Set_viewingMode();
            DesktopPane.add(statements);
            statements.setVisible(true);

        } else {

            statements.setBounds(62, -1, 1100, 550);
            DesktopPane.add(statements);
            statements.Set_viewingMode();
            statements.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        connection.ChangeIP();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void DateandTime() {
        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat date = new SimpleDateFormat("MMMM dd, yyyy");
        SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss a");

        //this.Date.setText(date.format(cal.getTime()));
        Time.setText(date.format(cal.getTime()) + " " + time.format(cal.getTime()));
    }

    public void RefreshTime() {
        TimerTask TT = new TimerTask() {
            @Override
            public void run() {
                DateandTime();
            }
        };

        Timer t = new Timer();
        t.scheduleAtFixedRate(TT, 1000, 1000);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCashar;
    private javax.swing.JMenu jMenuFinance;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuPrinsipals;
    private javax.swing.JMenu jMenuRegistrar;
    private javax.swing.JMenu jMenuViewing;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the User
     */
    public int getUser() {
        return User;
    }

    /**
     * @param User the User to set
     */
    public void setUser(int User) {
        this.User = User;

    }

    public void Set_DisplayUser(String name) {
        UserLabel.setText(name);

    }

    void setRegitrarMode() {
        Registrar();
    }

    @Override
    public synchronized void addWindowListener(WindowListener l) {
        super.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int op = JOptionPane.showConfirmDialog(locate(User, User), "System will close, Do you want or proceed?");

                if (op == 0) {
                    try {
                        Activity_log("System Log out", "Log out and System Close");
                        JOptionPane.showMessageDialog(locate(op, op), "System will log out");
                        System.exit(0);
                    } catch (IOException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {

                }

            }

            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("System Closed");

            }

        });

    }

    void Activity_log(String Activity, String Description) throws IOException {

        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());

            ps = c.prepareStatement("Insert into activity_log ( Activity_name, Description, Date, UseAccounts_idUseAccounts) values ('" + Activity + "','" + Description + "','" + timeStamp + "','" + User + "')");
            ps.execute();
            System.out.println("activity loged");

        } catch (SQLException ex) {
            Logger.getLogger(Section.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void Registrar() {
        jMenuItem2.setVisible(false);
        jMenuItem3.setVisible(false);
        jMenuItem5.setVisible(false);
        jMenuItem1.setVisible(false);
        jMenuItem7.setVisible(false);
        jMenuItem9.setVisible(false);

        jButton5.setVisible(true);
        jButton1.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton7.setVisible(false);

        jMenu3.setVisible(false);
        jMenu3.setEnabled(false);
        jMenuRegistrar.setVisible(true);
        jMenuRegistrar.setEnabled(true);
        jMenuCashar.setVisible(false);
        jMenuPrinsipals.setVisible(false);
        Registrar = true;

    }

    void Casher() {
        jMenu1.setVisible(false);
        jMenu3.setVisible(false);
        jMenu3.setEnabled(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);
        jMenuPrinsipals.setVisible(false);
        jMenuPrinsipals.setEnabled(false);
        jMenuViewing.setVisible(false);
        jMenuViewing.setEnabled(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);

        jButton5.setVisible(false);
        jButton1.setVisible(true);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton7.setVisible(true);
        jButton4.setVisible(false);

    }

    void Viewing() {

        if (statements == null) {
            statements = new Statements();
            statements.Set_viewingMode();
            statements.setBounds(62, -1, 1100, 550);
            DesktopPane.add(statements);
            statements.setVisible(true);
        } else {

            statements.setBounds(62, -1, 1100, 550);
            statements.Set_viewingMode();
            statements.setVisible(true);

        }

        jMenuItem2.setVisible(false);
        jMenuItem3.setVisible(false);
        jMenuItem5.setVisible(false);
        jMenuItem1.setVisible(false);
        jMenuItem7.setVisible(false);
        jMenuItem9.setVisible(false);

        jButton5.setVisible(true);
        jButton1.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton7.setVisible(false);

        jMenu3.setVisible(false);
        jMenu3.setEnabled(false);
        jMenuRegistrar.setVisible(true);
        jMenuRegistrar.setEnabled(true);
        jMenuCashar.setVisible(false);
        jMenuPrinsipals.setVisible(false);
        jMenu1.setVisible(false);
        jMenu3.setVisible(false);
        jMenu2.setEnabled(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jMenuRegistrar.setVisible(false);

    }

    void Principal() {
        jMenu1.setVisible(false);
        jMenu3.setVisible(false);

        jMenu2.setEnabled(false);

        jMenuCashar.setVisible(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);
        jMenuPrinsipals.setVisible(true);
        jMenuPrinsipals.setEnabled(true);
        jMenuViewing.setVisible(false);
        jMenuViewing.setEnabled(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);

        jButton5.setVisible(false);
        jButton1.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton7.setVisible(false);
        jButton4.setVisible(false);

    }

    void FinanceAdmin() {

        jMenu1.setVisible(true);
        jMenu3.setVisible(false);

        jMenu2.setEnabled(false);

        jMenuCashar.setVisible(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);
        jMenuPrinsipals.setVisible(false);
        jMenuPrinsipals.setEnabled(true);
        jMenuViewing.setVisible(false);
        jMenuViewing.setEnabled(false);
        jMenuFinance.setVisible(false);
        jMenuFinance.setEnabled(false);

        jButton5.setVisible(true);
        jButton1.setVisible(true);
        jButton8.setVisible(false);
        jButton9.setVisible(true);
        jButton7.setVisible(true);
        jButton4.setVisible(false);
    }

}
