package dcaa_billing;

import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class Select_Discount extends javax.swing.JFrame {
    DefaultTableModel model=new DefaultTableModel();
    String discountID=null;
    StudentBill studentBill=null;
    JMenuItem Select=new JMenuItem("Select");
    JPopupMenu menu=new JPopupMenu();
    Select_Discount main=this; 
    /**
     * Creates new form Select_Discount
     */
    public Select_Discount() {
        initComponents();
        model=(DefaultTableModel) jTable1.getModel();
        loadDiscounts();
       
        
        Select.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
             if ( discountID==null || discountID.equals("") ) {
              JOptionPane.showMessageDialog(main,"No discount selected");
        }else{
              studentBill.discountID = discountID;
              setVisible(false);
              studentBill.Computediscount();
              studentBill.RefreshBill();
              dispose();
          }
            
            }
        });
        
        menu.add(Select);
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    menu.show(e.getComponent(),e.getX(),e.getY());
                }
            }
            
            
});
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Button_Update_Select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Discount to implemented");
        setBounds(new java.awt.Rectangle(420, 93, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Discount ID", "Discount Name", "Value", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 400));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Select Discount");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, -1));

        Button_Update_Select.setText("Select Discount");
        Button_Update_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Update_SelectActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Update_Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 0)));
        discountID=String.valueOf(model.getValueAt(jTable1.getSelectedRow(),0));
        studentBill.discountID=discountID;
        System.out.println(studentBill.discountID);
    }//GEN-LAST:event_jTable1MouseClicked

    private void Button_Update_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Update_SelectActionPerformed
        // TODO add your handling code here:
          if ( discountID==null || discountID.equals("") ) {
              JOptionPane.showMessageDialog(this,"No discount selected");
        }else{
              studentBill.discountID = discountID;
              setVisible(false);
              studentBill.Computediscount();
              studentBill.RefreshBill();
              dispose();
          }
    }//GEN-LAST:event_Button_Update_SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_Discount().setVisible(true);
            }
        });
    }
    
    
    
    
      void loadDiscounts(){
        try {
            model.setRowCount(0);
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            int idDiscount = 0;
            ps = c.prepareStatement("Select idDiscounts, Discount_Name, Value,Type from discounts");
            rs = ps.executeQuery();
            while (rs.next()) {
                  model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
            System.out.println("Discounts Loaded");
        } catch (SQLException ex) {
            Logger.getLogger(Discounts.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
      
       public void setStudentBill(StudentBill a){
            studentBill=a;
   } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_Update_Select;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
