/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_billing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class Statements extends javax.swing.JInternalFrame {

    ArrayList<String> Sydisplay = new ArrayList<>();
    ArrayList<String> idSydisplay = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    private static DecimalFormat df2 = new DecimalFormat("#,###.##");

    double bills, Invoice, Balance;
    String Student_ID;
    Balances balmain;
    Name_Search search;
    JMenuItem Void = new JMenuItem("Void this Transaction?");
    JPopupMenu menu = new JPopupMenu();
    Login OverideLogin;
    Statements main;

    /**
     * Creates new form StudentInfo
     */
    public Statements() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        loadSY();
        main = this;
        Void.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 1)));
                System.out.println(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 5)));

                if (OverideLogin == null) {
                    OverideLogin = new Login();
                    OverideLogin.TitleText.setText("Override Verification");
                    OverideLogin.overide = true;
                    OverideLogin.setVisible(true);
                    OverideLogin.setReFerence_ORNum_for_Overide(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 1)), String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 5)), main);

                } else {
                    OverideLogin.overide = true;
                    OverideLogin.setVisible(true);
                    OverideLogin.setReFerence_ORNum_for_Overide(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 1)), String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 5)), main);

                }

            }

        });
        menu.add(Void);
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    menu.show(e.getComponent(), e.getX(), e.getY());

                }

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    void PrintStatement(String Id, String Sy) throws SQLException {
        try {
            JasperReport JR;
            JasperPrint JP;

            JasperDesign Jd = JRXmlLoader.load(System.getProperty("user.dir") + "\\\\reports\\\\Student_Bill_3.jrxml");
            String Location = System.getProperty("user.dir") + "\\\\reports\\\\";
            String SQL = "Select * from Billing where Student_Info_idStudent_Info='" + Id + "' AND School_Year_idSchool_Year='" + Sy + "' limit 1";

            JRDesignQuery JQ = new JRDesignQuery();
            JQ.setText(SQL);
            Jd.setQuery(JQ);
            JR = JasperCompileManager.compileReport(Jd);

            HashMap m = new HashMap<>();

            m.put("Full_Name", Student_name.getText());
            m.put("StudentId", StudentID.getText());
            m.put("SY", SchoolYear.getSelectedItem());
            m.put("Total_Bill", Tuition.getText());
            m.put("Total_Payment", Payment.getText());
            m.put("Total_Balance", TotalBalance.getText());
            m.put("SUBREPORT_DIR", Location);

            JP = JasperFillManager.fillReport(JR, m, DBConnection.getConnection());

            JasperViewer.viewReport(JP, false);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex);
            System.out.println(ex);

        }

    }

    void LoadStatement() {
        try {
            model.setRowCount(0);
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps, ps_chargeCheck, ps_checkBill, ps_Name;
            ResultSet rs, rs_charge, rs_checkbill, rs_name;

            ps_Name = c.prepareStatement("Select F_name,M_name,L_name from student_info where id ='" + StudentID.getText() + "'");
            rs_name = ps_Name.executeQuery();
            if (rs_name.next()) {
                Student_name.setText(rs_name.getString(1) + " " + rs_name.getString(2) + " " + rs_name.getString(3));
            }
            ps_Name.close();
            rs_name.close();

            ps = c.prepareStatement("Select DATE,Particulars,Category_of_charges_idCategory_of_charges,Value,OrNum from Invoice where Student_Info_idStudent_Info='" + StudentID.getText() + "' AND School_Year_idSchool_Year='" + String.valueOf(idSydisplay.get(SchoolYear.getSelectedIndex())) + "'");
            rs = ps.executeQuery();

            while (rs.next()) {
                String Description = "";
                double Charge = 0;

                ps_chargeCheck = c.prepareStatement("Select Fee_Name from fee_charges where idFee_Charges='" + rs.getString("Category_of_charges_idCategory_of_charges") + "'");
                rs_charge = ps_chargeCheck.executeQuery();
                if (rs_charge.next()) {
                    Description = rs_charge.getString(1);

                }
                rs_charge.close();

                ps_checkBill = c.prepareStatement("Select Amount from billing where ReferenceNo='" + rs.getString("Particulars") + "'");
                rs_checkbill = ps_checkBill.executeQuery();
                if (rs_checkbill.next()) {
                    Charge = rs_checkbill.getDouble(1);
                }
                rs_checkbill.close();

                model.addRow(new Object[]{rs.getString(1), rs.getString(2), Description, Charge, df2.format(rs.getDouble("Value")), rs.getString("OrNum")});

            }
            rs.close();
            ps.close();

            ps = c.prepareStatement("Select SUM(Amount) from billing where Student_Info_idStudent_Info='" + StudentID.getText() + "' AND School_Year_idSchool_Year='" + String.valueOf(idSydisplay.get(SchoolYear.getSelectedIndex())) + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                bills = rs.getDouble(1);
                Tuition.setText(df2.format(rs.getDouble(1)));

            }
            rs.close();
            ps.close();

            ps = c.prepareStatement("Select SUM(Value) from invoice where Student_Info_idStudent_Info='" + StudentID.getText() + "' AND School_Year_idSchool_Year='" + String.valueOf(idSydisplay.get(SchoolYear.getSelectedIndex())) + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                Invoice = rs.getDouble(1);
                Payment.setText(df2.format(Invoice));
            }

            rs.close();
            ps.close();
            Balance = bills - Invoice;
            TotalBalance.setText(df2.format(Balance));

        } catch (SQLException ex) {
            Logger.getLogger(Statements.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void loadSY() {
        try {

            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            ps = c.prepareStatement("Select idschool_year,School_Year,Semester from school_year");
            rs = ps.executeQuery();
            while (rs.next()) {
                Sydisplay.add(rs.getString(2) + "-" + rs.getString(3));
                idSydisplay.add(rs.getString(1));
            }
            rs.close();
            DefaultComboBoxModel SYBoxModel = new DefaultComboBoxModel(Sydisplay.toArray());
            SchoolYear.setModel(SYBoxModel);

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    void set_id(String id) {
        Student_ID = id;
        StudentID.setText(id);
        LoadStatement();
    }

    void set_id(String id, String sy) {
        Student_ID = id;
        StudentID.setText(id);
        SchoolYear.setSelectedIndex(idSydisplay.indexOf(sy));
        LoadStatement();
    }

    void set_BalanceMode(Balances cc) {
        balmain = cc;

    }

    void Set_viewingMode() {
        jButton3.setEnabled(false);
        StudentID.requestFocus();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Student_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SchoolYear = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Tuition = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TotalBalance = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setTitle("STATEMENT OF ACCOUTS");
        setMaximumSize(new java.awt.Dimension(1200, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setPreferredSize(new java.awt.Dimension(1100, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("DIGOS CENTRAL ADVENTIST ACADEMY");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 370, 20));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Lapu-lapu St., Zone III, Digos City");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 330, 20));

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("PAYMENT HISTORY");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 250, 20));

        Student_name.setBackground(new java.awt.Color(255, 255, 255));
        Student_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Student_name.setForeground(new java.awt.Color(0, 0, 0));
        Student_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 440, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("School Year:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 120, 20));

        StudentID.setBackground(new java.awt.Color(255, 255, 255));
        StudentID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        StudentID.setForeground(new java.awt.Color(0, 0, 0));
        StudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(StudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATE", "REFERENCE NO. ", "DESCRIPTION", "CHARGES AND FEES", "PAYMENTS", "OR Number"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1040, 180));

        SchoolYear.setBackground(new java.awt.Color(255, 255, 255));
        SchoolYear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SchoolYear.setForeground(new java.awt.Color(0, 0, 0));
        SchoolYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        SchoolYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolYearActionPerformed(evt);
            }
        });
        jPanel1.add(SchoolYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1060, 390));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Total Tution:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Load Statement");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Print Statement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1070, 60));

        Tuition.setBackground(new java.awt.Color(0, 0, 0));
        Tuition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tuition.setForeground(new java.awt.Color(0, 0, 0));
        Tuition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tuition.setText("1000.0000");
        Tuition.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Tuition, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 240, 30));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Total Payment:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 110, 30));

        Payment.setBackground(new java.awt.Color(0, 0, 0));
        Payment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Payment.setForeground(new java.awt.Color(0, 153, 102));
        Payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Payment.setText("1000.0000");
        Payment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 230, 30));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Total Balance:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, 30));

        TotalBalance.setBackground(new java.awt.Color(0, 0, 0));
        TotalBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalBalance.setForeground(new java.awt.Color(204, 0, 51));
        TotalBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalBalance.setText("1000.0000");
        TotalBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(TotalBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SchoolYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolYearActionPerformed

    private void StudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDActionPerformed
        // TODO add your handling code here:
        LoadStatement();
    }//GEN-LAST:event_StudentIDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LoadStatement();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(getBounds());
        if (balmain != null) {
            balmain.setAlwaysOnTop(true);
            setVisible(false);

        } else {
            setVisible(false);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (search == null) {
            search = new Name_Search();
            search.NameSearch_PaymentHistory(this);
            search.setVisible(true);
        } else {
            search.NameSearch_PaymentHistory(this);
            search.setVisible(true);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            PrintStatement(StudentID.getText(), idSydisplay.get(SchoolYear.getSelectedIndex()));
            System.out.println(idSydisplay.get(SchoolYear.getSelectedIndex()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(Statements.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Payment;
    private javax.swing.JComboBox<String> SchoolYear;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextField Student_name;
    private javax.swing.JLabel TotalBalance;
    private javax.swing.JLabel Tuition;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
