/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_billing;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class Add_Student_status extends javax.swing.JFrame {

    Discounts main;
    boolean update;
    String DiscountID;
    Student_Status_List status_List;
    boolean Update;
    String statusID;

    /**
     * Creates new form Add_Discount
     */
    public Add_Student_status() {
        initComponents();
        if (Update) {
            addDiscount.setText("Update");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Student_Status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        addDiscount = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW  STUDENT STATUS");
        setBounds(new java.awt.Rectangle(406, 173, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Status  Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 20));

        Student_Status.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel1.add(Student_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 34, 320, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Description.setColumns(20);
        Description.setLineWrap(true);
        Description.setRows(5);
        jScrollPane3.setViewportView(Description);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 320, 80));

        addDiscount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addDiscount.setText("ADD Status");
        addDiscount.setActionCommand("Add");
        addDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("New Student Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountActionPerformed
        // TODO add your handling code here:

        if (Update) {
            Update_student(statusID);
            status_List.loadData();
            this.dispose();

        } else {
            addDStudent_status();

        }

    }//GEN-LAST:event_addDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student_status().setVisible(true);
            }
        });
    }

    void set_Update(boolean update, String id, Discounts cc) {
        addDiscount.setText("Save Changes");
        main = cc;
        DiscountID = id;
        this.update = update;

    }

    void load_discountData() {

        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;

            ps = c.prepareStatement("Select Discount_Name, Value, Description, Type from discounts where idDiscounts='" + DiscountID + "'");
            rs = ps.executeQuery();

            if (rs.next()) {
                Student_Status.setText(rs.getString(1));
                // Discount.setText(rs.getString(2));
                Description.setText(rs.getString(3));
                //   DiscountCombox.setSelectedIndex(rs.getInt(4));

            }
            main.loadDiscounts();

        } catch (SQLException ex) {
            Logger.getLogger(Add_Student_status.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void addDStudent_status() {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;

            String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
            ps = c.prepareStatement("Insert into student_status_list (Student_Status_name, Description, createtime, updatetime, createdby) values" + "('" + Student_Status.getText() + "','" + Description.getText() + "' ,'" + timeStamp + "','" + timeStamp + "','2')");

            if (ps.execute()) {

            } else {
                JOptionPane.showMessageDialog(this, "New Student Status Successfully added");
                Student_Status.setText("");
                Description.setText("");
                Student_Status.requestFocus();
                status_List.loadData();

            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    void Update_student(String StatusID) {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
            System.out.println(statusID);
            ps = c.prepareStatement("Update student_status_list SET Student_Status_name='" + Student_Status.getText() + "', Description='" + Description.getText() + "', updatetime='" + timeStamp + "', createdby='" + 1 + "' where Student_statud_id='" + statusID + "' ");
            ps.execute();
            JOptionPane.showMessageDialog(this, "Status updated!", "Status update", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(StudentInfo_new.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void set_data(String Name, String Description, String StatusID, boolean update) {
        Student_Status.setText(Name);
        this.Description.setText(Description);
        statusID = StatusID;
        Update = update;
        if (update) {
            addDiscount.setText("Update");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField Student_Status;
    private javax.swing.JButton addDiscount;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
