/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_billing;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamie Eduardo Rosal <Jamiewertalmighty@gmail.com>
 */
public class Add_update_chargesandfees extends javax.swing.JFrame {

    DefaultComboBoxModel categoryBoxModel;
    ArrayList<String> cetegoryDisplay = new ArrayList<String>();
    ArrayList<String> idCategory = new ArrayList<String>();
    boolean update = false;
    int ID;
    String Fee_ID;
    Fees_Charges main;

    /**
     * Creates new form Add_update_chargesandfees
     */
    public Add_update_chargesandfees() {
        initComponents();
        load_cetgory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Particulars = new javax.swing.JTextField();
        Amount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FeeID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(358, 194, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD CHARGES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Particulars:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        Particulars.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel1.add(Particulars, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 400, -1));

        Amount.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel1.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Amount:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Category:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 20));

        FeeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FeeID.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(FeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Fee ID:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, -1));

        Category.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        jPanel1.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, -1));

        Description.setColumns(20);
        Description.setLineWrap(true);
        Description.setRows(5);
        jScrollPane3.setViewportView(Description);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 400, 100));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("ADD TO CHARGES");
        jButton5.setActionCommand("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (update) {
            Update_Fee();
        } else {
            SaveFee();
        }

        main.loaddata();
        dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_update_chargesandfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_update_chargesandfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_update_chargesandfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_update_chargesandfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_update_chargesandfees().setVisible(true);
            }
        });
    }

    void setUpdatemode(boolean mode, String id, Fees_Charges main) {
        update = mode;
        jButton5.setText("Save Changes");
        Fee_ID = id;
        this.main = main;

    }

    void set_Main(Fees_Charges cc) {
        this.main = cc;
    }

    void Load_data() {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            ps = c.prepareStatement("Select Fee_name,Description,Value,Category_of_charges,idFee_Charges from  fee_charges where  idFee_Charges= '" + Fee_ID + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                Particulars.setText(rs.getString(1));
                Description.setText(rs.getString(2));
                Amount.setText(rs.getString(3));
                FeeID.setText(rs.getString(5));
                Category.setSelectedIndex(idCategory.indexOf(rs.getString(4)));

            }

            main.loaddata();

        } catch (SQLException ex) {
            Logger.getLogger(Add_update_chargesandfees.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void SaveFee() {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;

            Calendar cal = Calendar.getInstance();
            cal.getTime();

            String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());

            int category = Integer.parseInt(idCategory.get(Category.getSelectedIndex()));

            ps = c.prepareStatement("Insert into  fee_charges (Fee_name,Description,Value,Category_of_charges,createtime,User)values" + "('" + Particulars.getText() + "','" + Description.getText() + "','" + Amount.getText() + "','" + category + "','" + timeStamp + "','100')");
            ps.execute();

            JOptionPane.showMessageDialog(this, "New Charge added ");

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    private void Update_Fee() {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;

            Calendar cal = Calendar.getInstance();
            cal.getTime();

            //String timeStamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
            int category = Integer.parseInt(idCategory.get(Category.getSelectedIndex()));

            ps = c.prepareStatement("Update fee_charges set Fee_name='" + Particulars.getText() + "',Description='" + Description.getText() + "',Value='" + Amount.getText() + "',Category_of_charges='" + category + "' where idFee_Charges='" + Fee_ID + "' ");
            ps.execute();
            JOptionPane.showMessageDialog(this, "Charge Updated ");
            main.loaddata();

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    void load_cetgory() {
        try {
            DBConnection.init();
            Connection c = DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs = null;
            ps = c.prepareStatement("Select idCategory_of_charges,Charge_Name from category_of_charges");
            rs = ps.executeQuery();
            while (rs.next()) {
                cetegoryDisplay.add(rs.getString(2));
                idCategory.add(rs.getString(1));
            }

            categoryBoxModel = new DefaultComboBoxModel(cetegoryDisplay.toArray());
            Category.setModel(categoryBoxModel);
            System.out.println(idCategory);

        } catch (SQLException ex) {
            Logger.getLogger(Add_update_chargesandfees.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Amount;
    public javax.swing.JComboBox<String> Category;
    public javax.swing.JTextArea Description;
    private javax.swing.JLabel FeeID;
    public javax.swing.JTextField Particulars;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
